---
settings:
  artifacts-dir: .

modules:
  signalfx:
    class: signalfx.signalfxplugin.SignalfxUploader

  # disable undesired modules
  ^grinder: null
  ^locust: null
  ^molotov: null
  ^cloud: null
  ^blazemeter: null
  ^proxy2jmx: null


cli-aliases:
  hw:
    reporting:
      - signalfx

---
modules:
  consolidator:
    ~percentiles:
      - 0.0
      - 50.0
      - 90.0
      - 95.0
      - 99.0
      - 99.9
      - 100.0
